using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ONEC.SUPPORT
{
    class Titulos
    {
       public static readonly ArrayList titulos = new ArrayList()
       {
        "ESO",
        "Bachiller",
        "FP Grado medio",
        "FP Grado superior",
        "Enseñanzas artísticas(regladas)",
        "Enseñanzas deportivas(regladas)",
        "Grado",
        "Licenciatura",
        "Diplomatura",
        "Ingeniería técnica",
        "Ingeniería superior",
        "Postgrado",
        "Máster",
        "Doctorado",
        "Otros títulos, certificaciones y carnés",
        "Otros cursos y certificación no reglada",
        "Ciclo formativo grado medio",
        "Ciclo formativo grado superior"
       };
        public static readonly ArrayList fp_medio = new ArrayList() {
        "Actividades agrarias",
         "Actividades físicas y deportivas",
         "Actividades marítimo-pesqueras",
         "Administración",
         "Artes gráficas",
         "Comercio y marketing",
         "Comunicacion",
         "imagen y sonido",
         "Edificación y obra civil",
         "Electricidad y electrónica",
         "Equipos e instalaciones electrotécnicas",
         "Fabricación mecánica",
         "Hostelería y turismo",
         "Imagen Personal",
         "Industrias alimentarias",
         "Informática",
         "Instalaciones frigoríficas y de climaticación",
         "Madera y mueble",
         "Mantenimiento de Vehículos autopropulsados",
         "Mantenimiento y servicios a la producción",
         "Química",
         "Sanidad",
         "Servicios socioculturales y a la comunidad",
         "Textil",
         "confección y piel",
         "Vidrio y cerámica",
        };

        public static readonly ArrayList fp_superior = new ArrayList() {
         "Actividades agrarias",
         "Actividades físicas y deportivas",
         "Actividades marítimo pesqueras",
         "Administración",
         "Administración y finanzas",
         "Artes gráficas",
         "Comercio internacional",
         "Comercio y marketing",
         "Comunicación",
         "imagen y sonido",
         "Edificación y obra civil",
         "Educación infantil",
         "Eficiencia energética y energía solar térmica",
         "Electricidad y electrónica",
         "Energía y agua",
         "Especialidad industrial",
         "Fabricación mecánica",
         "Hosteleríay turismo",
         "Imagen personal",
         "Industrias alimentarias",
         "Informática",
         "Madera y mueble",
         "Mantenimiento de vehículos autopropulsados",
         "Mantenimiento y servicios a la producción",
         "Prevención de riesgos profesionales",
         "Química",
         "Sanidad",
         "Secretariado",
         "Servicios al consumidor",
         "Servicios socioculturales y a la comunidad",
         "Sistemas de regulación y control automáticos",
         "Textil",
         "confección y piel",
         "Transporte y logística",
         "Vidrio y cerámica",
         "Técnico superior en interpretación de la lengua de signos",
        };


        public static readonly ArrayList ciclo_gradoMed = new ArrayList() {
        "Actividades físicas y deportivas",
         "Agraria",
         "Artes gráficas",
         "Comercio y marketing",
         "Imagen y sonido",
         "Edificación y obra civil",
         "Electricidad y eléctronica",
         "Energía y agua",
         "Fabricación mecánica",
         "Hostelería y turismo",
         "Imagen personal",
         "Industrias extractivas",
         "Informática y comunicaciones",
         "Madera",
         "mueble y corcho",
         "Instalación y mantenimiento",
         "Marítimo-pesqueras",
         "Química",
         "Sanidad",
         "Servicios socioculturales y a la comunidad",
         "Textil",
         "confección y piel",
         "Transporte y mantenimiento de vehículos",
         "Vidrio y cerámica",
         "Técnico en gestión administrativa",
         "Técnico en carrocería",
         "Técnico en emergencias y protección civil",
         "Técnico en equipos electrónicos de consumo",
         "Técnico en instalaciones de telecomunicaciones",
        };

        public static readonly ArrayList ciclo_gradoSup = new ArrayList() {
         "Artes y artesanías",
         "Energía y agua",
         "Administración y gestión",
         "Agraria",
         "Instalación y mantenimiento",
         "Artes gráficas",
         "Seguridad y medio ambiente",
         "Edificación y obra civil",
         "Electricidad y eléctronica",
         "Fabricación mecánica",
         "Físicas y deportivas",
         "Técnico superior en diseño en fabricación mecánica",
         "Hostelería y turismo",
         "Imagen personal",
         "Imagen y sonido",
         "Industrias Alimentarias",
         "Informática y comunicaciones",
         "Madera",
         "mueble y corcho",
         "Mantenimiento y servicios a la producción",
         "Marítimo-pesquera",
         "Química",
         "Sanidad",
         "Servicios socioculturales y a la comunidad",
         "Textil",
         "confección y piel",
         "Transporte y mantenimiento de vehículos",
         "Vidrio y cerámica",
         "Técnico superior en artes plásticas y diseño en animación",
         "Técnico superior en administración de sistemas informáticos en red",
         "Técnico superior en artes plásticas y diseño en proyectos y dirección de obras de decoración",
         "Técnico superior en audiología protésica",
         "Técnico superior en automatización y robótica industrial",
         "Técnico superior en coordinación de emergencias y protección civil",
         "Técnico superior en desarrollo de aplicaciones web",
         "Técnico superior en desarrollo de aplicaciones multiplataforma",
         "Técnico superior en dietética",
         "Técnico superior en diseño industrial(Deliniación)",
         "Técnico superior en educación infantil",
         "Técnico superior en educación y control ambiental",
         "Técnico superior en energias renovables",
         "Técnico superior en gestión forestal y el medio natural",
         "Técnico superior en instalaciones eléctricas y automáticas",
         "Técnico superior en integración social",
         "Técnico superior en interpretación de la lengua de signos",
         "Técnico superior en laboratorio de análisis clínicos",
         "Técnico superior en laboratorio de análisis y control de calidad",
         "Técnico superior en mantenimiento aeromecánico",
         "Técnico superior en mantenimiento de aviónica",
         "Técnico superior en mecatrónica industrial",
         "Técnico superior en plásticos y caucho",
         "Técnico superior en proyectos y dirección de obras de decoración",
         "Técnico superior en radioterapia",
         "Técnico superior en secretariado",
         "Técnico superior en sistemas de telecomunicaciones e informáticos",
         "Técnico superior en sistemas microinformáticos y redes",
         "Técnico superior en sonido para audiovisuales",
         "Técnico superior en sonido para audiovisuales y espectáculos",
         "Técnico superior en transporte y logística",
        };

        public static readonly ArrayList artisticas = new ArrayList() {
        "Enseñanzas de arte dramático",
         "Enseñanzas de artes plásticas y diseño",
         "Enseñanzas de danza",
         "Enseñanzas de música",
        };


        public static readonly ArrayList deportivas = new ArrayList() {
         "Enseñanzas de atletismo",
         "Enseñanzas de balonmano",
         "Enseñanzas de esquí",
         "Enseñanzas de fútbol",
         "Enseñanzas de montaña",
        };


        public static readonly ArrayList grados = new ArrayList() {
        "Grado Abierto",
         "Grado Abierto en Ciencias Sociales y Humanidades",
         "Grado Abierto en Ciencias Sociales y Jurídicas",
         "Grado Abierto en Ingeniería",
         "Grado en Administración de Empresas",
         "Grado en Administración de Empresas y Gestión de la Innovación",
         "Grado en Administración y Dirección de Empresas",
         "Grado en Administración y Dirección de Empresas Tecnológicas",
         "Grado en Administración y Gestión Pública",
         "Grado en Análisis de Negocios / Business Analytics",
         "Grado en Análisis Económico",
         "Grado en Animación",
         "Grado en Antropología Social",
         "Grado en Antropología Social y Cultural",
         "Grado en Antropología y Evolución Humana",
         "Grado en Arqueología",
         "Grado en Arquitectura",
         "Grado en Arquitectura",
         "Grado en Arquitectura Naval",
         "Grado en Arquitectura Naval e Ingeniería de Sistemas Marinos",
         "Grado en Arquitectura Naval e Ingeniería Marítima",
         "Grado en Arquitectura Técnica",
         "Grado en Arquitectura Técnica y Edificación",
         "Grado en Arte",
         "Grado en Artes",
         "Grado en Artes Digitales",
         "Grado en Artes Escénicas",
         "Grado en Artes Escénicas-Interpretación",
         "Grado en Artes Visuales y Danza",
         "Grado en Artes y Diseño",
         "Grado en Asistencia de Dirección",
         "Grado en Audiovisual y Multimedia",
         "Grado en Bellas Artes",
         "Grado en Bioinformática",
         "Grado en Bioingeniería",
         "Grado en Biología",
         "Grado en Biología Ambiental",
         "Grado en Biología Humana",
         "Grado en Biología Sanitaria",
         "Grado en Biomedicina",
         "Grado en Biomedicina Básica y Experimental",
         "Grado en Biomedicina y Terapias Avanzadas",
         "Grado en Bioquímica",
         "Grado en Bioquímica y Biología Molecular",
         "Grado en Bioquímica y Ciencias Biomédicas",
         "Grado en Biotecnología",
         "Grado en Business Data Analytics",
         "Grado en Ciencia de Datos",
         "Grado en Ciencia de Datos Aplicada",
         "Grado en Ciencia de Datos e Inteligencia Artificial",
         "Grado en Ciencia e Ingeniería de Datos",
         "Grado en Ciencia Política y Administración Pública",
         "Grado en Ciencia Política y de la Administración",
         "Grado en Ciencia Política y Gestión Pública",
         "Grado en Ciencia y Producción Animal",
         "Grado en Ciencia y Salud Animal",
         "Grado en Ciencia y Tecnología de la Edificación",
         "Grado en Ciencia y Tecnología de los Alimentos",
         "Grado en Ciencia y Tecnología Geográficas",
         "Grado en Ciencia, Gestión e Ingeniería de Servicios",
         "Grado en Ciencias",
         "Grado en Ciencias Agrarias y Bioeconomía",
         "Grado en Ciencias Ambientales",
         "Grado en Ciencias Biomédicas",
         "Grado en Ciencias Criminológicas y de la Seguridad",
         "Grado en Ciencias Culinarias y Gastronómicas",
         "Grado en Ciencias de la Actividad Física y del Deporte",
         "Grado en Ciencias de la Actividad Física y el Deporte",
         "Grado en Ciencias de la Cultura y Difusión Cultural",
         "Grado en Ciencias de la Seguridad",
         "Grado en Ciencias del Deporte",
         "Grado en Ciencias del Lenguaje y Estudios Literarios",
         "Grado en Ciencias del Mar",
         "Grado en Ciencias del Trabajo, Relaciones Laborales y Recursos Humanos",
         "Grado en Ciencias Empresariales",
         "Grado en Ciencias Empresariales - Management",
         "Grado en Ciencias Experimentales",
         "Grado en Ciencias Gastronómicas",
         "Grado en Ciencias Jurídicas de las Administraciones Públicas",
         "Grado en Ciencias Políticas",
         "Grado en Ciencias Políticas y de la Administración",
         "Grado en Ciencias Políticas y de la Administración Pública",
         "Grado en Ciencias Políticas y Gestión Pública",
         "Grado en Ciencias Sociales",
         "Grado en Ciencias y Lenguas de la Antigüedad",
         "Grado en Ciencias y Tecnologías Aplicadas al Deporte y al Acondicionamiento Físico",
         "Grado en Cine",
         "Grado en Cine y Cultura",
         "Grado en Cine y Medios Audiovisuales",
         "Grado en Cinematografía y Artes Audiovisuales",
         "Grado en Comercio",
         "Grado en Comercio Internacional",
         "Grado en Comercio y Marketing",
         "Grado en Comportamiento y Ciencias Sociales",
         "Grado en Composición de Músicas Contemporáneas",
         "Grado en Computación e Inteligencia Artificial",
         "Grado en Comunicación",
         "Grado en Comunicación / Bachelor of Communication",
         "Grado en Comunicación Audiovisual",
         "Grado en Comunicación Audiovisual y Multimedia",
         "Grado en Comunicación Audiovisual y Nuevos Medios",
         "Grado en Comunicación Corporativa, Protocolo y Organización de Eventos",
         "Grado en Comunicación Cultural",
         "Grado en Comunicación Digital",
         "Grado en Comunicación e Industrias Culturales",
         "Grado en Comunicación Global y Estratégica",
         "Grado en Comunicación Interactiva",
         "Grado en Comunicación Internacional",
         "Grado en Comunicación Publicitaria",
         "Grado en Comunicación y Creación Digital",
         "Grado en Comunicación y Medios Digitales",
         "Grado en Comunicación y Periodismo Audiovisual",
         "Grado en Comunicación y Relaciones Públicas",
         "Grado en Conservación y Restauración de Bienes Culturales",
         "Grado en Conservación y Restauración del Patrimonio Cultural",
         "Grado en Contabilidad y Finanzas",
         "Grado en Contenidos Digitales Interactivos",
         "Grado en Creación Artística para Videojuegos y Juegos Aplicados",
         "Grado en Creación Digital, Animación y Videojuegos",
         "Grado en Creación y Diseño",
         "Grado en Creación y Narración de Videojuegos",
         "Grado en Creación, Administración y Dirección de Empresas",
         "Grado en Criminalística: Ciencias y Tecnologías Forenses",
         "Grado en Criminología",
         "Grado en Criminología y Políticas Públicas de Prevención",
         "Grado en Criminología y Seguridad",
         "Grado en Danza",
         "Grado en Datos y Analítica de Negocio",
         "Grado en Derecho",
         "Grado en Derecho / Bachelor of Laws",
         "Grado en Desarrollo de Aplicaciones 3D Interactivas y Videojuegos",
         "Grado en Desarrollo de Videojuegos",
         "Grado en Dirección Comercial y Marketing",
         "Grado en Dirección de Empresas",
         "Grado en Dirección de Empresas (BBA)",
         "Grado en Dirección de Empresas en el Ámbito Digital",
         "Grado en Dirección de Empresas Tecnológicas",
         "Grado en Dirección Hotelera",
         "Grado en Dirección Internacional de Empresas",
         "Grado en Dirección Internacional de Empresas de Turismo y Ocio",
         "Grado en Dirección y Administración de Empresas",
         "Grado en Dirección y Creación de Empresas",
         "Grado en Dirección y Gestión de Empresas en el Ámbito Digital",
         "Grado en Dirección y Gestión Pública",
         "Grado en Diseño",
         "Grado en Diseño Arquitectónico de Interiores",
         "Grado en Diseño de Interiores",
         "Grado en Diseño de Moda",
         "Grado en Diseño de Producto",
         "Grado en Diseño de Productos Interactivos",
         "Grado en Diseño de Videojuegos",
         "Grado en Diseño Digital",
         "Grado en Diseño Digital y Multimedia",
         "Grado en Diseño Digital y Tecnologías Creativas",
         "Grado en Diseño Industrial y Desarrollo de Producto",
         "Grado en Diseño Integral y Gestión de la Imagen",
         "Grado en Diseño Multimedia y Gráfico",
         "Grado en Diseño Visual de Contenidos Digitales",
         "Grado en Diseño y Creación Digitales",
         "Grado en Diseño y Desarrollo de Videojuegos",
         "Grado en Diseño y Desarrollo de Videojuegos y Experiencias Interactivas",
         "Grado en Diseño y Gestión de Moda",
         "Grado en Diseño y Gestión de Proyectos",
         "Grado en Diseño y Producción de Videojuegos",
         "Grado en Diseño y Tecnologías Creativas",
         "Grado en Economía",
         "Grado en Economía Financiera y Actuarial",
         "Grado en Economía y Finanzas",
         "Grado en Economía y Gestión",
         "Grado en Economía y Negocios Internacionales",
         "Grado en Edificación",
         "Grado en Educación Infantil",
         "Grado en Educación Infantil",
         "Grado en Educación Primaria",
         "Grado en Educación Primaria",
         "Grado en Educación Social",
         "Grado en Empresa Internacional",
         "Grado en Empresa y Tecnología",
         "Grado en Empresa y Tecnología",
         "Grado en Empresas y Actividades Turísticas",
         "Grado en Enfermería",
         "Grado en Enología",
         "Grado en Español: Estudios Lingüísticos y Literarios",
         "Grado en Español: Lengua y Literatura",
         "Grado en Español: Lengua y Literaturas",
         "Grado en Estadística",
         "Grado en Estadística Aplicada",
         "Grado en Estadística Empresarial",
         "Grado en Estadística y Empresa",
         "Grado en Estudios Alemanes",
         "Grado en Estudios Árabes e Islámicos",
         "Grado en Estudios Árabes y Hebreos",
         "Grado en Estudios Clásicos",
         "Grado en Estudios Clásicos y Románicos",
         "Grado en Estudios de Arquitectura",
         "Grado en Estudios de Arquitectura",
         "Grado en Estudios de Asia Oriental (Chino)",
         "Grado en Estudios de Asia Oriental (Coreano)",
         "Grado en Estudios de Asia Oriental (Japonés)",
         "Grado en Estudios de Asia y África: Árabe, Chino y Japonés",
         "Grado en Estudios de Catalán y Español",
         "Grado en Estudios de Español y Chino: Lengua, Literatura y Cultura",
         "Grado en Estudios de Inglés y Catalán",
         "Grado en Estudios de Inglés y de Clásicas",
         "Grado en Estudios de Inglés y Español",
         "Grado en Estudios de Inglés y Francés",
         "Grado en Estudios de la Arquitectura",
         "Grado en Estudios en Arquitectura",
         "Grado en Estudios Franceses",
         "Grado en Estudios Francófonos Aplicados",
         "Grado en Estudios Globales / Global Studies",
         "Grado en Estudios Hebreos y Arameos",
         "Grado en Estudios Hispánicos",
         "Grado en Estudios Hispánicos, Lengua Española y sus Literaturas",
         "Grado en Estudios Hispano-Alemanes",
         "Grado en Estudios Ingleses",
         "Grado en Estudios Ingleses. Lengua, Literatura y Cultura",
         "Grado en Estudios Internacionales",
         "Grado en Estudios Internacionales de Economía y Empresa",
         "Grado en Estudios Italianos",
         "Grado en Estudios Literarios",
         "Grado en Estudios Portugueses y Brasileños",
         "Grado en Estudios Semíticos e Islámicos",
         "Grado en Estudios Socioculturales de Género",
         "Grado en Estudios Vascos",
         "Grado en Farmacia",
         "Grado en Filología",
         "Grado en Filología Catalana",
         "Grado en Filología Catalana y Estudios Occitanos",
         "Grado en Filología Catalana: Estudios de Literatura y Lingüística",
         "Grado en Filología Clásica",
         "Grado en Filología Hispánica",
         "Grado en Filología Moderna. Inglés",
         "Grado en Filología Vasca-Euskal Filologia",
         "Grado en Filosofía",
         "Grado en Filosofía, Política y Economía",
         "Grado en Finanzas y Contabilidad",
         "Grado en Finanzas, Banca y Seguros",
         "Grado en Fiscalidad y Administración Pública",
         "Grado en Física",
         "Grado en Física e Instrumentación Espacial",
         "Grado en Fisioterapia",
         "Grado en Fotografía",
         "Grado en Fundamentos de Arquitectura",
         "Grado en Fundamentos de Arquitectura y Urbanismo",
         "Grado en Gallego y Portugués: Estudios Lingüísticos y Literarios",
         "Grado en Gastronomía",
         "Grado en Gastronomía y Artes Culinarias",
         "Grado en Genética",
         "Grado en Geografía",
         "Grado en Geografía e Historia",
         "Grado en Geografía y Gestión del Territorio",
         "Grado en Geografía y Medio Ambiente",
         "Grado en Geografía y Ordenación del Territorio",
         "Grado en Geografía, Análisis Territorial y Sostenibilidad",
         "Grado en Geografía, Medio Ambiente y Planificación Territorial",
         "Grado en Geografía, Ordenación del Territorio y Gestión del Medio Ambiente",
         "Grado en Geología",
         "Grado en Gestión Aeronáutica",
         "Grado en Gestión Aplicada",
         "Grado en Gestión Comercial y Marketing",
         "Grado en Gestión Cultural",
         "Grado en Gestión de Ciudades Inteligentes y Sostenibles",
         "Grado en Gestión de Empresas de Comercio y Distribución",
         "Grado en Gestión de Información y Contenidos Digitales",
         "Grado en Gestión de Información y Documentación Digital",
         "Grado en Gestión de la Ciberseguridad",
         "Grado en Gestión de la Información y Contenidos Digitales",
         "Grado en Gestión de Negocios",
         "Grado en Gestión de Pequeñas y Medianas Empresas",
         "Grado en Gestión de Seguridad Pública",
         "Grado en Gestión de Sistemas de Información",
         "Grado en Gestión del Turismo",
         "Grado en Gestión Deportiva",
         "Grado en Gestión Digital de Información y Documentación",
         "Grado en Gestión Económico Financiera",
         "Grado en Gestión Empresarial Basada en el Análisis de Datos",
         "Grado en Gestión Hotelera y Turística",
         "Grado en Gestión Industrial de la Moda",
         "Grado en Gestión Informática Empresarial",
         "Grado en Gestión Turística y Hotelera",
         "Grado en Gestión Urbana / Bachelor of Urban Management",
         "Grado en Gestión y Administración Pública",
         "Grado en Gestión y Marketing Empresarial",
         "Grado en Gestión y Operaciones del Transporte Aéreo",
         "Grado en Gobernanza Global, Economía y Orden Legal",
         "Grado en Historia",
         "Grado en Historia del Arte",
         "Grado en Historia del Arte y Arqueología",
         "Grado en Historia del Arte y Gestión del Patrimonio Artístico",
         "Grado en Historia del Arte y Patrimonio Histórico-Artístico",
         "Grado en Historia y Ciencias de la Música",
         "Grado en Historia y Ciencias de la Música y Tecnología Musical",
         "Grado en Historia y Geografía",
         "Grado en Historia y Patrimonio",
         "Grado en Historia y Patrimonio Histórico",
         "Grado en Historia y Política",
         "Grado en Historia, Geografía e Historia del Arte",
         "Grado en Humanidades",
         "Grado en Humanidades Digitales Globales",
         "Grado en Humanidades y Estudios Culturales",
         "Grado en Humanidades y Estudios Sociales",
         "Grado en Humanidades y Patrimonio",
         "Grado en Humanidades: Estudios Interculturales",
         "Grado en Humanidades: Historia Cultural",
         "Grado en Industria Digital",
         "Grado en Información y Documentación",
         "Grado en Informática y Servicios",
         "Grado en Ingeniería Aeroespacial",
         "Grado en Ingeniería Aeroespacial en Aeronavegación",
         "Grado en Ingeniería Aeroespacial en Aeronaves",
         "Grado en Ingeniería Aeroespacial en Transporte y Aeropuertos",
         "Grado en Ingeniería Aeroespacial en Vehículos Aeroespaciales",
         "Grado en Ingeniería Agraria",
         "Grado en Ingeniería Agraria y Alimentaria",
         "Grado en Ingeniería Agraria y del Medio Rural",
         "Grado en Ingeniería Agraria y Energética",
         "Grado en Ingeniería Agrícola",
         "Grado en Ingeniería Agrícola y Agroalimentaria",
         "Grado en Ingeniería Agrícola y del Medio Rural",
         "Grado en Ingeniería Agroalimentaria",
         "Grado en Ingeniería Agroalimentaria y Agroambiental",
         "Grado en Ingeniería Agroalimentaria y de Sistemas Biológicos",
         "Grado en Ingeniería Agroalimentaria y del Medio Rural",
         "Grado en Ingeniería Agroambiental",
         "Grado en Ingeniería Agroambiental y del Paisaje",
         "Grado en Ingeniería Alimentaria",
         "Grado en Ingeniería Ambiental",
         "Grado en Ingeniería Biomédica",
         "Grado en Ingeniería Civil",
         "Grado en Ingeniería Civil - Construcciones Civiles",
         "Grado en Ingeniería Civil - Hidrología",
         "Grado en Ingeniería Civil - Transportes y Servicios Urbanos",
         "Grado en Ingeniería Civil en Construcciones Civiles",
         "Grado en Ingeniería Civil en Hidrología",
         "Grado en Ingeniería Civil en Transportes y Servicios Urbanos",
         "Grado en Ingeniería Civil y Territorial",
         "Grado en Ingeniería de Automoción",
         "Grado en Ingeniería de Bioprocesos",
         "Grado en Ingeniería de Computadores",
         "Grado en Ingeniería de Comunicaciones Móviles y Espaciales",
         "Grado en Ingeniería de Datos",
         "Grado en Ingeniería de Diseño Industrial",
         "Grado en Ingeniería de Diseño Industrial y Desarrollo del Producto",
         "Grado en Ingeniería de Diseño y Tecnología Textil",
         "Grado en Ingeniería de Edificación",
         "Grado en Ingeniería de Energía",
         "Grado en Ingeniería de Energía y Medio Ambiente",
         "Grado en Ingeniería de Energías Renovables",
         "Grado en Ingeniería de la Ciberseguridad",
         "Grado en Ingeniería de la Edificación",
         "Grado en Ingeniería de la Energía",
         "Grado en Ingeniería de la Hortofruticultura y Jardinería",
         "Grado en Ingeniería de la Salud",
         "Grado en Ingeniería de la Seguridad",
         "Grado en Ingeniería de la Tecnología de Minas y Energía",
         "Grado en Ingeniería de la Tecnología Minera",
         "Grado en Ingeniería de las Explotaciones Agropecuarias",
         "Grado en Ingeniería de las Industrias Agrarias y Alimentarias",
         "Grado en Ingeniería de las Tecnologías de la Información Geoespacial",
         "Grado en Ingeniería de las Tecnologías de Telecomunicación",
         "Grado en Ingeniería de los Recursos Energéticos",
         "Grado en Ingeniería de los Recursos Energéticos, Combustibles y Explosivos",
         "Grado en Ingeniería de los Recursos Mineros",
         "Grado en Ingeniería de los Recursos Mineros y Energéticos",
         "Grado en Ingeniería de Materiales",
         "Grado en Ingeniería de Obras Públicas",
         "Grado en Ingeniería de Obras Públicas en Construcciones Civiles",
         "Grado en Ingeniería de Obras Públicas en Transportes y Servicios Urbanos",
         "Grado en Ingeniería de Organización",
         "Grado en Ingeniería de Organización Industrial",
         "Grado en Ingeniería de Procesos Químicos Industriales",
         "Grado en Ingeniería de Recursos Energéticos",
         "Grado en Ingeniería de Recursos Minerales",
         "Grado en Ingeniería de Recursos Mineros y Energéticos",
         "Grado en Ingeniería de Redes de Telecomunicación",
         "Grado en Ingeniería de Sistemas Aeroespaciales",
         "Grado en Ingeniería de Sistemas Audiovisuales",
         "Grado en Ingeniería de Sistemas Audiovisuales de Telecomunicación",
         "Grado en Ingeniería de Sistemas Biológicos",
         "Grado en Ingeniería de Sistemas de Comunicaciones",
         "Grado en Ingeniería de Sistemas de Información",
         "Grado en Ingeniería de Sistemas de Telecomunicación",
         "Grado en Ingeniería de Sistemas de Telecomunicación, Sonido e Imagen",
         "Grado en Ingeniería de Sistemas Electrónicos",
         "Grado en Ingeniería de Sistemas TIC",
         "Grado en Ingeniería de Sistemas y Servicios de Telecomunicaciones",
         "Grado en Ingeniería de Sonido e Imagen",
         "Grado en Ingeniería de Tecnología de Minas y Energía",
         "Grado en Ingeniería de Tecnología y Diseño Textil",
         "Grado en Ingeniería de Tecnologías de Caminos",
         "Grado en Ingeniería de Tecnologías de Telecomunicación",
         "Grado en Ingeniería de Tecnologías Específicas de Telecomunicación",
         "Grado en Ingeniería de Tecnologías Industriales",
         "Grado en Ingeniería de Tecnologías Mineras",
         "Grado en Ingeniería de Tecnologías y Servicios de Telecomunicación",
         "Grado en Ingeniería del Automóvil",
         "Grado en Ingeniería del Medio Natural",
         "Grado en Ingeniería del Software",
         "Grado en Ingeniería Eléctrica",
         "Grado en Ingeniería Eléctrica y Electrónica",
         "Grado en Ingeniería Electromecánica",
         "Grado en Ingeniería Electrónica",
         "Grado en Ingeniería Electrónica de Comunicaciones",
         "Grado en Ingeniería Electrónica de Telecomunicación",
         "Grado en Ingeniería Electrónica Industrial",
         "Grado en Ingeniería Electrónica Industrial y Automática",
         "Grado en Ingeniería Electrónica y Automática",
         "Grado en Ingeniería Electrónica y Automática Industrial",
         "Grado en Ingeniería Electrónica, Robótica y Mecatrónicav",
         "Grado en Ingeniería en Automoción",
         "Grado en Ingeniería en Desarrollo de Contenidos Digitales",
         "Grado en Ingeniería en Diseño Industrial",
         "Grado en Ingeniería en Diseño Industrial y Desarrollo de Productos",
         "Grado en Ingeniería en Diseño Mecánico",
         "Grado en Ingeniería en Ecotecnologías en Procesos Industriales",
         "Grado en Ingeniería en Electrónica Industrial",
         "Grado en Ingeniería en Electrónica Industrial y Automática",
         "Grado en Ingeniería en Electrónica y Automática Industrial",
         "Grado en Ingeniería en Energías Renovables y Eficiencia Energética",
         "Grado en Ingeniería en Explotación de Minas y Recursos Energéticos",
         "Grado en Ingeniería en Geoinformación y Geomática",
         "Grado en Ingeniería en Geomática y Topografía",
         "Grado en Ingeniería en Industria Conectada",
         "Grado en Ingeniería en Informática",
         "Grado en Ingeniería en Informática de Sistemas",
         "Grado en Ingeniería en Innovación de Procesos y Productos",
         "Grado en Ingeniería en Matemática Aplicada al Análisis de Datos",
         "Grado en Ingeniería en Organización de las Tecnologías de la Información y de la Comunicación",
         "Grado en Ingeniería en Organización Industrial",
         "Grado en Ingeniería en Organización Industrial y Logística",
         "Grado en Ingeniería en Química Industrial",
         "Grado en Ingeniería en Recursos Energéticos y Mineros",
         "Grado en Ingeniería en Sistemas Audiovisuales y Multimedia",
         "Grado en Ingeniería en Sistemas de Telecomunicación",
         "Grado en Ingeniería en Sistemas Industriales",
         "Grado en Ingeniería en Sistemas y Tecnología Naval",
         "Grado en Ingeniería en Sonido e Imagen",
         "Grado en Ingeniería en Tecnología de Telecomunicación",
         "Grado en Ingeniería en Tecnología Industrial",
         "Grado en Ingeniería en Tecnología Minera",
         "Grado en Ingeniería en Tecnología Naval",
         "Grado en Ingeniería en Tecnologías Aeroespaciales",
         "Grado en Ingeniería en Tecnologías Ambientales",
         "Grado en Ingeniería en Tecnologías de la Telecomunicación",
         "Grado en Ingeniería en Tecnologías de Telecomunicación",
         "Grado en Ingeniería en Tecnologías Industriales",
         "Grado en Ingeniería en Vehículos Aeroespaciales",
         "Grado en Ingeniería Energética",
         "Grado en Ingeniería Física",
         "Grado en Ingeniería Forestal",
         "Grado en Ingeniería Forestal y del Medio Natural",
         "Grado en Ingeniería Forestal: Industrias Forestales",
         "Grado en Ingeniería Geológica",
         "Grado en Ingeniería Geomática",
         "Grado en Ingeniería Geomática y Topografía",
         "Grado en Ingeniería Hortofrutícola y Jardinería",
         "Grado en Ingeniería Informática",
         "Grado en Ingeniería Informática de Gestión y Sistemas de Información",
         "Grado en Ingeniería Informática de Servicios y Aplicaciones",
         "Grado en Ingeniería Informática del Software",
         "Grado en Ingeniería Informática en Ingeniería de Computadores",
         "Grado en Ingeniería Informática en Ingeniería del Software",
         "Grado en Ingeniería Informática en Sistemas de Información",
         "Grado en Ingeniería Informática en Tecnologías de la Información",
         "Grado en Ingeniería Informática y Tecnologías Virtuales",
         "Grado en Ingeniería Informática-Ingeniería de Computadores",
         "Grado en Ingeniería Informática-Tecnologías Informáticas",
         "Grado en Ingeniería Marina",
         "Grado en Ingeniería Marítima",
         "Grado en Ingeniería Matemática",
         "Grado en Ingeniería Matemática en Ciencia de Datos",
         "Grado en Ingeniería Mecánica",
         "Grado en Ingeniería Mecatrónica",
         "Grado en Ingeniería Mecatrónica y Robótica",
         "Grado en Ingeniería Minera",
         "Grado en Ingeniería Minera y Energética",
         "Grado en Ingeniería Multimedia",
         "Grado en Ingeniería Náutica y Transporte Marítimo",
         "Grado en Ingeniería Naval y Oceánica",
         "Grado en Ingeniería Química",
         "Grado en Ingeniería Química Industrial",
         "Grado en Ingeniería Radioelectrónica",
         "Grado en Ingeniería Radioelectrónica Naval",
         "Grado en Ingeniería Robótica",
         "Grado en Ingeniería Telemática",
         "Grado en Ingeniería Telemática en Telecomunicaciones",
         "Grado en Ingeniería y Gestión Empresarial",
         "Grado en Ingeniería y Sistemas de Datos",
         "Grado en Inglés",
         "Grado en Inglés: Estudios Lingüísticos y Literarios",
         "Grado en Innovación en Procesos y Productos Alimentarios",
         "Grado en Innovación y Seguridad Alimentaria",
         "Grado en Inteligencia Artificial",
         "Grado en Inteligencia de Negocios",
         "Grado en Inteligencia de Negocios",
         "Grado en Inteligencia Robótica",
         "Grado en Inteligencia y Analítica de Negocios",
         "Grado en Interpretación de Música Moderna",
         "Grado en Interpretación Musical",
         "Grado en Lengua de Signos Española y Comunidad Sorda",
         "Grado en Lengua Española y Literaturas Hispánicas",
         "Grado en Lengua Española y su Literatura",
         "Grado en Lengua Española y sus Literaturas",
         "Grado en Lengua y Cultura Vasca",
         "Grado en Lengua y Literatura Alemanas",
         "Grado en Lengua y Literatura Catalanas",
         "Grado en Lengua y Literatura Española",
         "Grado en Lengua y Literatura Españolas",
         "Grado en Lengua y Literatura Gallegas",
         "Grado en Lengua y Literatura Hispánica",
         "Grado en Lengua y Literatura Hispánicas",
         "Grado en Lengua y Literatura Inglesas",
         "Grado en Lenguas Aplicadas",
         "Grado en Lenguas Extranjeras",
         "Grado en Lenguas Modernas",
         "Grado en Lenguas Modernas y Gestión",
         "Grado en Lenguas Modernas y sus Literaturas",
         "Grado en Lenguas Modernas y Traducción",
         "Grado en Lenguas Modernas, Cultura y Comunicación",
         "Grado en Lenguas Románicas y sus Literaturas",
         "Grado en Lenguas y Literaturas Modernas",
         "Grado en Lenguas y Literaturas Modernas, Francés - Inglés",
         "Grado en Lenguas y Literaturas Modernas-Francés",
         "Grado en Lenguas y Literaturas Modernas-Portugués",
         "Grado en Lenguas, Literaturas y Culturas Románicas",
         "Grado en Liderazgo Emprendedor e Innovación",
         "Grado en Lingüística",
         "Grado en Lingüística Aplicada y Ciencias del Lenguaje",
         "Grado en Lingüística y Lenguas Aplicadas",
         "Grado en Literatura General y Comparada",
         "Grado en Literatura y Escritura Creativa",
         "Grado en Literaturas Comparadas",
         "Grado en Logística Empresarial",
         "Grado en Logística y Negocios Marítimos",
         "Grado en Logopedia",
         "Grado en Maestro de Educación Infantil",
         "Grado en Maestro de Educación Primaria",
         "Grado en Maestro en Educación Infantil",
         "Grado en Maestro en Educación Primaria",
         "Grado en Marina",
         "Grado en Marketing",
         "Grado en Marketing e Investigación de Mercados",
         "Grado en Marketing e Investigación de Mercados",
         "Grado en Marketing y Comercialización Internacional",
         "Grado en Marketing y Comunicación",
         "Grado en Marketing y Comunicación Digital",
         "Grado en Marketing y Comunicación Empresarial",
         "Grado en Marketing y Comunidades Digitales",
         "Grado en Marketing y Dirección Comercial",
         "Grado en Marketing y Gestión Comercial",
         "Grado en Matemática Aplicada",
         "Grado en Matemática Aplicada y Computación",
         "Grado en Matemática Computacional",
         "Grado en Matemática Computacional y Analítica de Datos",
         "Grado en Matemáticas",
         "Grado en Matemáticas e Informática",
         "Grado en Matemáticas y Estadística",
         "Grado en Medicina",
         "Grado en Medio Ambiente y Sostenibilidad",
         "Grado en Medios Audiovisuales",
         "Grado en Microbiología",
         "Grado en Multimedia",
         "Grado en Multimedia y Artes Digitales",
         "Grado en Multimedia. Aplicaciones y Videojuegos",
         "Grado en Música",
         "Grado en Musicología",
         "Grado en Nanociencia y Nanotecnología",
         "Grado en Náutica y Transporte Marítimo",
         "Grado en Negocios Internacionales",
         "Grado en Negocios Internacionales",
         "Grado en Negocios y Marketing Internacionales",
         "Grado en Nutrición Humana y Dietética",
         "Grado en Odontología",
         "Grado en Óptica y Optometría",
         "Grado en Óptica, Optometría y Audiología",
         "Grado en Organización de Eventos, Protocolo y Relaciones Institucionales",
         "Grado en Paisaje",
         "Grado en Paisajismo",
         "Grado en Pedagogía",
         "Grado en Periodismo",
         "Grado en Periodismo y Comunicación Corporativa",
         "Grado en Piloto de Aviación Comercial y Operaciones Aéreas",
         "Grado en Podología",
         "Grado en Política, Derecho y Economía",
         "Grado en Prevención y Seguridad Integral",
         "Grado en Protocolo y Organización de Eventos",
         "Grado en Protocolo, Organización de Eventos y Comunicación Corporativa",
         "Grado en Psicología",
         "Grado en Publicidad",
         "Grado en Publicidad y Relaciones Públicas",
         "Grado en Publicidad, Marketing y Relaciones Públicas",
         "Grado en Publicidad, Relaciones Públicas y Marketing",
         "Grado en Química",
         "Grado en Relaciones Internacionales",
         "Grado en Relaciones Internacionales",
         "Grado en Relaciones Internacionales y Unión Europea",
         "Grado en Relaciones Laborales",
         "Grado en Relaciones Laborales y Desarrollo de Recursos Humanos",
         "Grado en Relaciones Laborales y Empleo",
         "Grado en Relaciones Laborales y Ocupación",
         "Grado en Relaciones Laborales y Recursos Humanos",
         "Grado en Seguridad",
         "Grado en Seguridad y Control de Riesgos",
         "Grado en Seguros y Finanzas",
         "Grado en Sistemas de Información",
         "Grado en Sociología",
         "Grado en Sociología Aplicada",
         "Grado en Sonido e Imagen en Telecomunicación",
         "Grado en Técnicas Cuantitativas para la Economía y la Empresa",
         "Grado en Técnicas de Aplicaciones de Software",
         "Grado en Técnicas de Interacción Digital y de Computación",
         "Grado en Tecnología de la Ingeniería Civil",
         "Grado en Tecnología e Innovación Alimentaria",
         "Grado en Tecnologías de Caminos, Canales y Puertos",
         "Grado en Tecnologías de la Información",
         "Grado en Tecnologías Industriales y Análisis Económico",
         "Grado en Tecnologías Interactivas",
         "Grado en Tecnologías Marinas",
         "Grado en Tecnologías para la Sociedad de la Información",
         "Grado en Tecnologías y Servicios de Telecomunicación",
         "Grado en Terapia Ocupacional",
         "Grado en Trabajo Social",
         "Grado en Traducción e Interpretación",
         "Grado en Traducción e Interpretación: Inglés - Alemán",
         "Grado en Traducción e Interpretación: Inglés - Francés",
         "Grado en Traducción y Comunicación Intercultural",
         "Grado en Traducción y Mediación Interlingüística",
         "Grado en Traducción, Interpretación y Lenguas Aplicadas",
         "Grado en Transporte y Logística",
         "Grado en Turismo",
         "Grado en Turismo y Gestión del Ocio",
         "Grado en Turismo y Ocio",
         "Grado en Veterinaria",
         };


        public static readonly ArrayList licenciatura = new ArrayList() {
        "Administración y direccción de empresas",
         "Antropologísa social y cultural",
         "Bellas artes",
         "Biología",
         "Bioquímica",
         "Biotecnología",
         "Ciencia y tecnología de los alimentos",
         "Ciencias actuariales y financieras",
         "Ciencias ambientales",
         "Ciencias de la actividad física y del deporte",
         "Ciencias del mar",
         "Ciencias del trabajo",
         "Ciencias políticas y de la administración",
         "Cincias químicas",
         "Ciencias religiosas",
         "Ciencias y técnicas estadísticas",
         "Comunicación audiovisual",
         "Criminología",
         "Derecho",
         "Documentación",
         "Economía",
         "Enología",
         "Estudios de asia oriental",
         "Farmacia",
         "Filología alemana",
         "Filología arabe",
         "Filología catalana",
         "Filología clásica",
         "Filología eslava",
         "Filología francesa",
         "Filología gallega",
         "Filología hebrea",
         "Filología hispánica",
         "Filología inglesa",
         "Filología italiana",
         "Filología portuguesa",
         "Filología romántica",
         "Filología vasca",
         "Filosofía",
         "Física",
         "Geografía",
         "Geología",
         "Historia",
         "Historia del arte",
         "Historia y ciencias de la música",
         "Humanidades",
         "Investigación y técnicas de mercado",
         "Lingüistica",
         "Maquinas navales",
         "Maketing",
         "Matemáticas",
         "Medicina",
         "Náutica y transporte marítimo",
         "Odontología",
         "Pedagogía",
         "Periodismo",
         "Psicología",
         "Psicopedagogía",
         "Publicidad y relaciones públicas",
         "Química",
         "Radioelectrónica naval",
         "Sociología",
         "Teoría de la literatura y literatura comparada",
         "Traducción e interpretación",
         "Veterinaria",
        };

        public static readonly ArrayList diplomatura = new ArrayList() {
        "Biblioteconomía y documentación",
         "Ciencias empresariales",
         "Educación social",
         "Enfermería",
         "Estadística",
         "Fisiterapia",
         "Gestión y administración pública",
         "Logopedia",
         "Maestro: Especialidad de audición y lenguaje",
         "Maestro: Especialidad de educación especial",
         "Maestro: Especialidad de educación física",
         "Maestro: Especialidad de educación infantil",
         "Maestro: Especialidad de educación musical",
         "Maestro: Especialidad de educación primaria",
         "Maestro: Especialidad de lengua extranjera",
         "Máquinas navales",
         "Navegación marítima",
         "Nutrición humana y dietética",
         "Óptica y Optometría",
         "Podología",
         "Protocolo y relaciones institucionales",
         "Radioelectrónica naval",
         "Relaciones laborales",
         "Terapia ocupacional",
         "Trabajo social",
         "Turismo",
        };


        public static readonly ArrayList ing_tec = new ArrayList() {
         "Aeronáutico",
         "Aeronáutico, especialidad en aeromotores",
         "Aeronáutico, especialidad en aeronavegación",
         "Aeronáutico, especialidad en aeronaves",
         "Aeronáutico, especialidad en aeropuertos",
         "Aeronáutico, especialidad en equipos y materiales aeroespaciales",
         "Agrícola",
         "Agrícola, especialidad en explotaciones agropecuarias",
         "Agrícola, especialidad en hortofruticultura y jardinería",
         "Agrícola, especialidad en industrias agrarias y alimentarias",
         "Agrícola, especialidad en mecanización y construcciones rurales",
         "Arquitecto técnico",
         "Forestal",
         "Forestal, especialidad en explotaciones forestales",
         "Forestal, especialidad en industrias forestales",
         "Industrial",
         "Industrial, especialidad en electricidad",
         "Industrial, especialidad en electrónica industrial",
         "Industrial, especialidad en mecánica",
         "Industrial, especialidad en química industrial",
         "Industrial, especialidad textil",
         "Naval",
         "Naval, especialidad en estructura marina",
         "Naval, especialidad en propulsión y servicios del buque",
         "Técnico de minas",
         "Técnico de minas, especialidad en explotación de minas",
         "Técnico de minas, especialidad en instalaciones electromecánicas mineras",
         "Técnico de minas, especialidad en mineralurgia y metalurgia",
         "Técnico de minas, especialidad en recursos energéticos, combustibles y explosivos",
         "Técnico de minas, especialidad en sondeos y prospecciones mineras",
         "Técnico de obras públicas",
         "Técnico de obras públicas, especialidad en construcciones civiles",
         "Técnico de obras públicas, especialidad en hidrología",
         "Técnico de obras públicas, especialidad en transportes y servicios urbanos",
         "Técnico de telecomunicación",
         "Técnico de telecomunicación, especialidad en sistemas de telecomunicación",
         "Técnico de telecomunicación, especialidad en sistemas electrónicos",
         "Técnico de telecomunicación, especialidad en sonido e imagen",
         "Técnico de telecomunicación, especialidad en telemática",
         "Técnico en diseño industrial",
         "Técnico en informática de gestión",
         "Técnico en informática de sistemas",
         "Técnico en topografía",
        };


        public static readonly ArrayList ing_sup = new ArrayList() {
        "Aeronáutico",
         "Agrónomo",
         "Arquitecto",
         "Geólogo",
         "Industrial",
         "Ingeniero de caminos, canales y puertos",
         "Ingeniero de materiales",
         "Ingeniero de minas",
         "Ingeniero de montes",
         "Ingeniero de sistemas de defensa",
         "Ingeniero de telecomunicación",
         "Ingeniero en automática y electrónica industrial",
         "Ingeniero en electrónica",
         "Ingeniero en geodesia y cartografía",
         "Ingeniero en informática",
         "Ingeniero en organización industrial",
         "Naval y oceánico",
         "Químico",
        };

        public static readonly ArrayList doctorado = new ArrayList() {
         "Álgebra",
         "Análisis geográfico regional",
         "Análisis matemático",
         "Anatomía patológica",
         "Anatomía y anatomía patológica comparadas",
         "Anatomía y embriología humana",
         "Antropología física",
         "Antropología social",
         "Arqueología",
         "Arquitectura y tecnología de computadores",
         "Astronomía y astrofísica",
         "Biblioteconomía y documentación",
         "Biología celular",
         "Biomedicina",
         "Bioquímica y biología molecular",
         "Botánica",
         "Ciencia de la computación e inteligencia artificial",
         "Ciencia de los materiales e ingeniería metalúrgica",
         "Ciencia política y de la administración",
         "Ciencias y técnicas de la navegación",
         "Ciencias y técnicas historiográficas",
         "Cirugía",
         "Comercialización e investigación de mercados",
         "Composición arquitectónica",
         "Comunicación audiovisual y publicidad",
         "Construcciones arquitectónicas",
         "Construcciones navales",
         "Cristalografía y mineralogía",
         "Derecho administrativo",
         "Derecho civil",
         "Derecho constitucional",
         "Derecho del trabajo y de la seguridad social",
         "Derecho eclesiástico del estado",
         "Derecho financiero y tributario",
         "Derecho internacional privado",
         "Derecho internacional público y relaciones internacionales",
         "Derecho mercantil",
         "Derecho penal",
         "Derecho procesal",
         "Derecho romano",
         "Dermatología",
         "Dibujo",
         "Didáctica de la expresión corporal",
         "Didáctica de la expresión musical",
         "Didáctica de la expresión musical, plástica y corporal(desagregada)",
         "Didáctica de la expresión plástica",
         "Didáctica de la lengua y la literatura",
         "Didáctica de la matemática",
         "Didáctica de las ciencias experimentales",
         "Didáctica de las ciencias sociales",
         "Didáctica y organización escolar",
         "Ecología",
         "Economía aplicada",
         "Economía financiera y contabilidad",
         "Economía, sociología y política agraria",
         "Edafología y química agrícola",
         "Educación física y deportiva",
         "Electromagnetismo",
         "Electrónica",
         "Enfermería",
         "Escultura",
         "Estadística e investigación operativa",
         "Estética y teoría de las artes",
         "Estomatología",
         "Estratigrafía",
         "Estudios arabes e islámicos",
         "Estudios hebreos y arameos",
         "Explotación de minas",
         "Expresión gráfica arquitectónica",
         "Expresión gráfica en la ingeniería",
         "Farmacia y tecnología farmaceútica",
         "Farmacología",
         "Filología alemana",
         "Filología catalana",
         "Filología eslava",
         "Filología francesa",
         "Filología gallega y portuguesa",
         "Filología griega",
         "Filología hispánica",
         "Filología inglesa",
         "Filología italiana",
         "Filología latina",
         "Filología romántica",
         "Filología vasca",
         "Filosofía",
         "Filosofía del derecho",
         "Filosofía moral",
         "Física aplicada",
         "Física atómica, molecular y nuclear",
         "Física de la materia condensada",
         "Física de la tierra",
         "Física teórica",
         "Fisiología",
         "Fisiología vegetal",
         "Fisioterapia",
         "Fundamentos del análisis económico",
         "Genética",
         "Geodesia y geomática",
         "Geodinámica externa",
         "Geodinámica interna",
         "Geografía física",
         "Geografía humana",
         "Geometría y topología",
         "Histología",
         "Historia antigua",
         "Historia contemporánea",
         "Historia de América",
         "Historia de la ciencia",
         "Historia del arte",
         "Historia del derecho y las instituciones",
         "Historia del pensamiento y de los movimientos sociales",
         "Historia e instituciones económicas",
         "Historia medieval",
         "Historia moderna",
         "Ingeniería aeroespacial",
         "Ingeniería agroforestal",
         "Ingeniería biomédica",
         "Ingeniería cartográfica, geodésica y fotogrametría",
         "Ingeniería de la construcción",
         "Ingeniería de los procesos de la fabricación",
         "Ingeniería de sistemas y automática",
         "Ingeniería del terreno",
         "Ingeniería e infraestructura de los transportes",
         "Ingeniería eléctrica",
         "Ingeniería hidráulica",
         "Ingeniería mecánica",
         "Ingeniería nuclear",
         "Ingeniería química",
         "Ingeniería telemática",
         "Ingeniería textil y papelera",
         "Inmunología",
         "Lengua española",
         "Lengua y cultura del extremo oriente",
         "Lenguajes y sistemas informáticos",
         "Lingüistica general",
         "Lingüistica indoeuropea",
         "Literatura española",
         "Lógica y filosofía de la ciencia",
         "Máquinas y motores térmicos",
         "Matemática aplicada",
         "Mecánica de fluidos",
         "Mecánica de medios contínuos y teoría de estructuras",
         "Medicina",
         "Medicina legal y forense",
         "Medicina preventiva y salud pública",
         "Medicina y cirugía animal",
         "Metodología de las ciencias del comportamiento",
         "Métodos de investigación y diagnóstico en educación",
         "Microbiología",
         "Nutrición y bromatología",
         "Obstetricia y ginecología",
         "Oftalmología",
         "Óptica",
         "Organización de empresas",
         "Otorrinolaringología",
         "Paleontología",
         "Parasitología",
         "Pediatría",
         "Periodismo",
         "Personalidad, evaluación y tratamiento psicológico",
         "Petrología y geoquímica",
         "Pintura",
         "Prehistoria",
         "Producción animal",
         "Producción vegetal",
         "Prospección e investigación minera",
         "Proyectos arquitectónicos",
         "Proyectos de ingeniería",
         "Psicobiología",
         "Psicología básica",
         "Psicología evolutiva y de la educación",
         "Psicología social",
         "Psiquiatría",
         "Química analítica",
         "Química física",
         "Química inorgánica",
         "Química orgánica",
         "Radiología y medicina física",
         "Sanidad animal",
         "Sociología",
         "Tecnología de alimentos",
         "Tecnología electrónica",
         "Tecnología del medio ambiente",
         "Teoría de la literatura y literatura comparada",
         "Teoría de la señal y comunicaciones",
         "Teoría e historia de la educación",
         "Toxicología",
         "Trabajo social y servicios sociales",
         "Traducción e interpretación",
         "Urbanística y ordenacióndel territorio",
         "Zoología",
        };

    }
}
